name: untitled11
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  pdf: ^3.10.1
  printing: ^5.12.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.8
  telephony: ^0.2.0
  fluttertoast: ^8.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # <-- Moved here properly

flutter_launcher_icons:   # <-- ADDED correctly outside dependencies
  android: true
  ios: true
  image_path: "lib/assets/logo1.png"  # <-- make sure logo1.png exists

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
